global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  scrape_timeout: 2s # the global default (10s).

  external_labels:
      monitor: 'data-node'

scrape_configs:
  - job_name: 'openresty'
    metrics_path: '/status/format/prometheus'
    static_configs:
      - targets: ['openresty:80']